name: CustomRecipes
version: '${project.version}'
main: de.canstein_berlin.customrecipes.CustomRecipes
api-version: 1.20
authors: [ Hasenzahn1 ]

commands:
  listrecipes:
    description: Open the gui to display the recipes